import React, { useEffect, useRef, useState } from "react";
import { useReportStore } from "../../../stores/reportStore";
import { VisionService } from "../../../services/visionService";
import AnalysisTimeline from "../ai/AnalysisTimeline";
import AIAnalysisCard from "../ai/AIAnalysisCard";
import EditableSummaryCard from "../ai/EditableSummaryCard";
import { Button } from "../../ui/button";
import { ArrowLeft, ArrowRight, RefreshCw, ShieldAlert } from "lucide-react";
import { AIAnalysisResult } from "../../../ai/models/types";

// Hard-cap: if AI + timeline haven't finished within this time, force-proceed
const UI_TIMEOUT_MS = 18_000;

interface Step2AIAnalysisProps {
  onNext: () => void;
  onBack: () => void;
}

export const Step2AIAnalysis: React.FC<Step2AIAnalysisProps> = ({ onNext, onBack }) => {
  const { draft, setDraftAIAnalysis } = useReportStore();
  const [analysisLoading, setAnalysisLoading] = useState(false);
  const [timelineComplete, setTimelineComplete] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [manualFallback] = useState<AIAnalysisResult>(() => ({
    category: "road_damage",
    subcategory: "Pothole / Road Surface Crack",
    severity: "high",
    confidence: 82,
    title: "Infrastructure Issue Detected",
    description:
      "A community infrastructure issue has been recorded. The AI Vision analysis was completed with fallback mode — a manual review will be scheduled by the responsible department.",
    detectedObjects: ["road surface", "infrastructure defect"],
    possibleHazards: ["Vehicle damage risk", "Pedestrian hazard"],
    departmentSuggestion: "Roads & Infrastructure Department",
    contextFactors: ["Urban road", "High traffic area"],
    urgencyReason: "Requires departmental inspection and repair.",
    processingTimeMs: 0,
  }));
  const uiTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const analysisDoneRef = useRef(false);

  // Clear the safety timeout
  const clearUiTimeout = () => {
    if (uiTimeoutRef.current) {
      clearTimeout(uiTimeoutRef.current);
      uiTimeoutRef.current = null;
    }
  };

  // Force UI out of loading after UI_TIMEOUT_MS, no matter what
  const startUiTimeout = (fallback: AIAnalysisResult) => {
    uiTimeoutRef.current = setTimeout(() => {
      console.warn("[Step2AIAnalysis] UI safety timeout fired — forcing timeline complete");
      if (!analysisDoneRef.current) {
        analysisDoneRef.current = true;
        setDraftAIAnalysis(fallback);
      }
      setAnalysisLoading(false);
      setTimelineComplete(true);
    }, UI_TIMEOUT_MS);
  };

  const startAnalysis = async () => {
    if (!draft.media?.file) return;

    setAnalysisLoading(true);
    setError(null);
    setTimelineComplete(false);
    analysisDoneRef.current = false;

    // Start safety timeout
    startUiTimeout(manualFallback);

    try {
      console.log("[Step2AIAnalysis] Calling VisionService.analyzeMedia...");

      const analysisResult = await VisionService.analyzeMedia(
        draft.media.file,
        draft.userDescription,
        draft.location
          ? {
              lat: draft.location.lat,
              lng: draft.location.lng,
              address: draft.location.address,
            }
          : undefined
      );

      console.log("[Step2AIAnalysis] Analysis completed — storing result");
      analysisDoneRef.current = true;
      setDraftAIAnalysis(analysisResult);
    } catch (err: any) {
      console.warn("[Step2AIAnalysis] AI analysis failed:", err.message || err);
      setError(
        err?.message ||
          "AI Vision analysis failed. Please check your connection and retry."
      );
    } finally {
      clearUiTimeout();
      setAnalysisLoading(false);
    }
  };

  useEffect(() => {
    if (!draft.aiAnalysis && !analysisLoading) {
      startAnalysis();
    }
    return () => clearUiTimeout();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // The UI is "loading" if:
  //   - analysis is still running AND there is no error
  //   - or the timeline animation has not completed yet
  const showLoader = !error && (analysisLoading || !timelineComplete);

  const handleTimelineComplete = () => {
    console.log("[Step2AIAnalysis] AnalysisTimeline animation completed");
    setTimelineComplete(true);
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-lg font-bold text-gray-900">AI Vision Diagnosis</h2>
        <p className="text-sm text-gray-500 mt-1">
          Review the analysis results generated by Gemini Vision. You can edit any field.
        </p>
      </div>

      {showLoader ? (
        <div className="py-8">
          <AnalysisTimeline
            isProcessing={analysisLoading}
            onComplete={handleTimelineComplete}
          />
        </div>
      ) : error ? (
        <div className="space-y-4 text-center">
          <div className="flex flex-col items-center justify-center p-4 text-sm text-red-800 bg-red-50 rounded-xl border border-red-100">
            <div className="flex items-center mb-2">
              <ShieldAlert className="w-5 h-5 mr-2 shrink-0 text-red-500" />
              <span>AI analysis failed</span>
            </div>
            <p>{error}</p>
          </div>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
            <Button variant="outline" onClick={startAnalysis}>
              <RefreshCw className="w-4 h-4 mr-2" />
              Retry Analysis
            </Button>
            <Button
              variant="secondary"
              onClick={() => {
                setDraftAIAnalysis(manualFallback);
                setError(null);
                setTimelineComplete(true);
              }}
            >
              Use Manual Fallback
            </Button>
          </div>
        </div>
      ) : (
        <div className="space-y-6 animate-card-slide-up">
          {/* Main Visuals Card */}
          <AIAnalysisCard />

          {/* Editable fields */}
          <EditableSummaryCard />
        </div>
      )}

      <div className="flex justify-between pt-4 border-t border-gray-100">
        <Button variant="outline" onClick={onBack} disabled={analysisLoading}>
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Button>
        <Button onClick={onNext} disabled={showLoader || !!error} className="px-6">
          Set Location
          <ArrowRight className="w-4 h-4 ml-2" />
        </Button>
      </div>
    </div>
  );
};
export default Step2AIAnalysis;
